#' Groundfish diversity
#'
#' Description...
#'
#' @format Format with columns...
#'
#' \itemize{
#'     \item year: ...
#'     \item index: ...
#'     \item SEup: ...
#'     \item SElo: ...
#'     \item timeseries: ...
#'     \item metric: ...
#' }
#'
#' @details Example for more info: More information available at \url{https://noaa-edab.github.io/tech-doc/aquaculture.html}
#' @concept dataset_other
"groundfish"
